website:
  favicon: favicon.svg
  navbar:
    tools:
      - icon: github
        href: https://github.com/ruslan-basyrov/acuity
    left:
      - text: "Home"
        href: https://ruslanbasyrov.com

project:
  type: acuity
  render:
    - "index.qmd"

format:
  acuity-html: default
    
  acuity-typst:
    keep-typ: true
